# Copyright 2024 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.5.4-r1

EAPI=8

CRATES="
	adler@1.0.2
	binfarce@0.2.1
	miniz_oxide@0.6.2
"

MY_PN="cargo-auditable"
MY_PV="0.6.1"
MY_P="${MY_PN}-${MY_PV}"

inherit cargo

DESCRIPTION="Command-line tool to extract the dependency trees embedded in binaries"
HOMEPAGE="https://github.com/rust-secure-code/cargo-auditable/tree/master/rust-audit-info"
SRC_URI="
	https://github.com/rust-secure-code/${MY_PN}/archive/v${MY_PV}.tar.gz -> ${MY_P}.tar.gz
	${CARGO_CRATE_URIS}
"

LICENSE="|| ( Apache-2.0 MIT )"
# Dependent crate licenses
LICENSE+=" MIT"
SLOT="0"
KEYWORDS="~amd64"

S="${WORKDIR}/${MY_P}/${PN}"

# rust does not use *FLAGS from make.conf, silence portage warning
# update with proper path to binaries this crate installs, omit leading /
QA_FLAGS_IGNORED="usr/bin/${PN}"
