# Copyright 2023-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.16.0

EAPI=8

CRATES="
	adler2@2.0.1
	aho-corasick@1.1.5
	ansi_colours@1.2.3
	anstream@1.0.0
	anstyle@1.0.14
	anstyle-parse@1.0.0
	anstyle-query@1.1.5
	anstyle-wincon@3.0.11
	anyhow@1.0.104
	autocfg@1.5.1
	base64@0.22.1
	bat@0.26.1
	bincode@1.3.3
	bit-set@0.8.0
	bit-vec@0.8.0
	bitflags@2.13.1
	bstr@1.13.1
	bytemuck@1.25.2
	bytesize@1.3.3
	cargo-subcommand-metadata@0.1.0
	cfg-if@1.0.4
	clap@4.6.6
	clap-cargo@0.19.0
	clap_builder@4.6.6
	clap_derive@4.6.4
	clap_lex@1.1.0
	clircle@0.6.1
	colorchoice@1.0.5
	console@0.16.4
	content_inspector@0.2.4
	convert_case@0.10.0
	crc32fast@1.5.0
	crossbeam-channel@0.5.16
	crossbeam-utils@0.8.22
	crossterm@0.29.0
	crossterm_winapi@0.9.1
	darling@0.23.0
	darling_core@0.23.0
	darling_macro@0.23.0
	deranged@0.5.8
	derive_more@2.1.1
	derive_more-impl@2.1.1
	document-features@0.2.12
	either@1.17.0
	encode_unicode@1.0.0
	encoding_rs@0.8.35
	equivalent@1.0.2
	errno@0.3.14
	fancy-regex@0.16.2
	fastrand@2.5.0
	flate2@1.1.9
	fnv@1.0.7
	fs-err@3.3.1
	getrandom@0.4.3
	globset@0.4.20
	grep-cli@0.1.12
	hashbrown@0.17.1
	heck@0.5.0
	home@0.5.12
	ident_case@1.0.1
	indexmap@2.14.0
	is_terminal_polyfill@1.70.2
	itertools@0.14.0
	itoa@1.0.18
	libc@0.2.189
	linux-raw-sys@0.12.1
	litrs@1.0.0
	lock_api@0.4.14
	log@0.4.33
	memchr@2.8.3
	miniz_oxide@0.8.9
	minus@5.7.2
	mio@1.2.2
	nu-ansi-term@0.50.3
	num-conv@0.2.2
	once_cell@1.21.4
	once_cell_polyfill@1.70.2
	parking_lot@0.12.5
	parking_lot_core@0.9.12
	path_abs@0.5.1
	plist@1.10.0
	powerfmt@0.2.0
	prettyplease@0.2.37
	prettyplease@0.3.0
	proc-macro2@1.0.107
	quick-xml@0.41.0
	quote@1.0.47
	r-efi@6.0.0
	redox_syscall@0.5.18
	regex@1.13.1
	regex-automata@0.4.18
	regex-syntax@0.8.11
	rgb@0.8.53
	rustc_version@0.4.1
	rustix@1.1.4
	ryu@1.0.23
	same-file@1.0.6
	scopeguard@1.2.0
	semver@1.0.28
	serde@1.0.229
	serde_core@1.0.229
	serde_derive@1.0.229
	serde_spanned@1.1.1
	serde_with@3.22.0
	serde_with_macros@3.22.0
	serde_yaml@0.9.34+deprecated
	shell-words@1.1.1
	shlex@2.0.1
	signal-hook@0.3.18
	signal-hook-mio@0.2.5
	signal-hook-registry@1.4.8
	simd-adler32@0.3.10
	smallvec@1.15.2
	std_prelude@0.2.12
	strsim@0.11.1
	syn@2.0.119
	syn@3.0.3
	syn-select-next@0.4.0-alpha.1
	syntect@5.3.0
	tempfile@3.27.0
	termcolor@1.4.1
	terminal-colorsaurus@1.0.3
	terminal-trx@0.2.6
	textwrap@0.16.2
	thiserror@2.0.20
	thiserror-impl@2.0.20
	time@0.3.55
	time-core@0.1.9
	time-macros@0.2.32
	toml@0.9.12+spec-1.1.0
	toml@1.1.4+spec-1.1.0
	toml_datetime@0.7.5+spec-1.1.0
	toml_datetime@1.1.1+spec-1.1.0
	toml_parser@1.1.3+spec-1.1.0
	toml_writer@1.1.2+spec-1.1.0
	toolchain_find@0.5.1
	unicode-ident@1.0.24
	unicode-segmentation@1.13.3
	unicode-width@0.2.2
	unsafe-libyaml@0.2.11
	utf8parse@0.2.2
	walkdir@2.5.0
	wasi@0.11.1+wasi-snapshot-preview1
	winapi@0.3.9
	winapi-i686-pc-windows-gnu@0.4.0
	winapi-util@0.1.11
	winapi-x86_64-pc-windows-gnu@0.4.0
	windows@0.56.0
	windows-core@0.56.0
	windows-implement@0.56.0
	windows-interface@0.56.0
	windows-link@0.2.1
	windows-result@0.1.2
	windows-sys@0.61.2
	windows-targets@0.52.6
	windows_aarch64_gnullvm@0.52.6
	windows_aarch64_msvc@0.52.6
	windows_i686_gnu@0.52.6
	windows_i686_gnullvm@0.52.6
	windows_i686_msvc@0.52.6
	windows_x86_64_gnu@0.52.6
	windows_x86_64_gnullvm@0.52.6
	windows_x86_64_msvc@0.52.6
	winnow@0.7.15
	winnow@1.0.4
	xterm-color@1.0.2
"

inherit cargo

DESCRIPTION="Subcommand to show the result of macro expansion and #[derive] expansion"
HOMEPAGE="https://github.com/dtolnay/cargo-expand"
SRC_URI="
	https://github.com/dtolnay/${PN}/archive/${PV}.tar.gz -> ${P}.tar.gz
	${CARGO_CRATE_URIS}
"

LICENSE="|| ( Apache-2.0 MIT )"
# Dependent crate licenses
LICENSE+=" Apache-2.0 BSD LGPL-3+ MIT Unicode-3.0"
SLOT="0"
KEYWORDS="~amd64"

RUST_MIN_VER="1.88.0"

# rust does not use *FLAGS from make.conf, silence portage warning
# update with proper path to binaries this crate installs, omit leading /
QA_FLAGS_IGNORED="usr/bin/${PN}"

src_install() {
	cargo_src_install
	einstalldocs
}
