# Copyright 2023-2024 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.5.4-r1

EAPI=8

CRATES="
	adler@1.0.2
	aho-corasick@1.1.3
	ansi_colours@1.2.2
	anstream@0.6.14
	anstyle@1.0.7
	anstyle-parse@0.2.4
	anstyle-query@1.0.3
	anstyle-wincon@3.0.3
	autocfg@1.3.0
	base64@0.21.7
	bat@0.24.0
	bincode@1.3.3
	bit-set@0.5.3
	bit-vec@0.6.3
	bitflags@1.3.2
	bitflags@2.5.0
	bstr@1.9.1
	bytemuck@1.16.0
	bytesize@1.3.0
	cargo-subcommand-metadata@0.1.0
	cfg-if@1.0.0
	clap@4.5.4
	clap_builder@4.5.2
	clap_derive@4.5.4
	clap_lex@0.7.0
	clircle@0.4.0
	colorchoice@1.0.1
	console@0.15.8
	content_inspector@0.2.4
	crc32fast@1.4.0
	deranged@0.3.11
	encode_unicode@0.3.6
	encoding_rs@0.8.34
	equivalent@1.0.1
	errno@0.3.9
	fancy-regex@0.11.0
	fastrand@2.1.0
	flate2@1.0.30
	fnv@1.0.7
	fs-err@2.11.0
	globset@0.4.14
	grep-cli@0.1.10
	hashbrown@0.14.5
	heck@0.5.0
	home@0.5.9
	indexmap@2.2.6
	is_terminal_polyfill@1.70.0
	itoa@1.0.11
	lazy_static@1.4.0
	libc@0.2.153
	line-wrap@0.2.0
	linux-raw-sys@0.4.14
	log@0.4.21
	memchr@2.7.2
	miniz_oxide@0.7.2
	nu-ansi-term@0.49.0
	num-conv@0.1.0
	once_cell@1.19.0
	path_abs@0.5.1
	plist@1.6.1
	powerfmt@0.2.0
	prettyplease@0.2.20
	proc-macro2@1.0.82
	quick-xml@0.31.0
	quote@1.0.36
	regex@1.10.4
	regex-automata@0.4.6
	regex-syntax@0.8.3
	rgb@0.8.37
	rustix@0.38.34
	ryu@1.0.18
	same-file@1.0.6
	semver@1.0.23
	serde@1.0.202
	serde_derive@1.0.202
	serde_json@1.0.117
	serde_spanned@0.6.6
	serde_yaml@0.9.34+deprecated
	shell-words@1.1.0
	shlex@1.3.0
	std_prelude@0.2.12
	strsim@0.11.1
	syn@2.0.64
	syn-select@0.3.0
	syntect@5.2.0
	tempfile@3.10.1
	termcolor@1.4.1
	thiserror@1.0.60
	thiserror-impl@1.0.60
	time@0.3.36
	time-core@0.1.2
	time-macros@0.2.18
	toml@0.8.13
	toml_datetime@0.6.6
	toml_edit@0.22.13
	toolchain_find@0.4.0
	unicode-ident@1.0.12
	unicode-width@0.1.12
	unsafe-libyaml@0.2.11
	utf8parse@0.2.1
	walkdir@2.5.0
	winapi@0.3.9
	winapi-i686-pc-windows-gnu@0.4.0
	winapi-util@0.1.8
	winapi-x86_64-pc-windows-gnu@0.4.0
	windows-sys@0.48.0
	windows-sys@0.52.0
	windows-targets@0.48.5
	windows-targets@0.52.5
	windows_aarch64_gnullvm@0.48.5
	windows_aarch64_gnullvm@0.52.5
	windows_aarch64_msvc@0.48.5
	windows_aarch64_msvc@0.52.5
	windows_i686_gnu@0.48.5
	windows_i686_gnu@0.52.5
	windows_i686_gnullvm@0.52.5
	windows_i686_msvc@0.48.5
	windows_i686_msvc@0.52.5
	windows_x86_64_gnu@0.48.5
	windows_x86_64_gnu@0.52.5
	windows_x86_64_gnullvm@0.48.5
	windows_x86_64_gnullvm@0.52.5
	windows_x86_64_msvc@0.48.5
	windows_x86_64_msvc@0.52.5
	winnow@0.6.8
"

inherit cargo

DESCRIPTION="Subcommand to show the result of macro expansion and #[derive] expansion."
HOMEPAGE="https://github.com/dtolnay/cargo-expand"
SRC_URI="
	https://github.com/dtolnay/${PN}/archive/${PV}.tar.gz -> ${P}.tar.gz
	${CARGO_CRATE_URIS}
"

LICENSE="|| ( Apache-2.0 MIT )"
# Dependent crate licenses
LICENSE+=" Apache-2.0 BSD LGPL-3+ MIT Unicode-DFS-2016"
SLOT="0"
KEYWORDS="~amd64"

BDEPEND=">=virtual/rust-1.70"

# rust does not use *FLAGS from make.conf, silence portage warning
# update with proper path to binaries this crate installs, omit leading /
QA_FLAGS_IGNORED="usr/bin/${PN}"

src_install() {
	cargo_src_install
	einstalldocs
}
