# Copyright 2023-2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.5.4-r1

EAPI=8

CRATES="
	adler2@2.0.0
	aho-corasick@1.1.3
	ansi_colours@1.2.3
	anstream@0.6.18
	anstyle@1.0.10
	anstyle-parse@0.2.6
	anstyle-query@1.1.2
	anstyle-wincon@3.0.6
	autocfg@1.4.0
	base64@0.22.1
	bat@0.24.0
	bincode@1.3.3
	bit-set@0.5.3
	bit-vec@0.6.3
	bitflags@1.3.2
	bitflags@2.6.0
	bstr@1.11.3
	bytemuck@1.21.0
	bytesize@1.3.0
	cargo-subcommand-metadata@0.1.0
	cfg-if@1.0.0
	clap@4.5.23
	clap-cargo@0.15.1
	clap_builder@4.5.23
	clap_derive@4.5.18
	clap_lex@0.7.4
	clircle@0.4.0
	colorchoice@1.0.3
	console@0.15.10
	content_inspector@0.2.4
	crc32fast@1.4.2
	deranged@0.3.11
	encode_unicode@1.0.0
	encoding_rs@0.8.35
	equivalent@1.0.1
	errno@0.3.10
	etcetera@0.8.0
	fancy-regex@0.11.0
	fastrand@2.3.0
	flate2@1.0.35
	fnv@1.0.7
	fs-err@3.0.0
	getrandom@0.2.15
	globset@0.4.15
	grep-cli@0.1.11
	hashbrown@0.15.2
	heck@0.5.0
	home@0.5.11
	indexmap@2.7.0
	is_terminal_polyfill@1.70.1
	itoa@1.0.14
	libc@0.2.169
	linux-raw-sys@0.4.14
	log@0.4.22
	memchr@2.7.4
	miniz_oxide@0.8.2
	nu-ansi-term@0.49.0
	num-conv@0.1.0
	once_cell@1.20.2
	path_abs@0.5.1
	plist@1.7.0
	powerfmt@0.2.0
	prettyplease@0.2.27
	proc-macro2@1.0.92
	quick-xml@0.32.0
	quote@1.0.38
	regex@1.11.1
	regex-automata@0.4.9
	regex-syntax@0.8.5
	rgb@0.8.50
	rustix@0.38.42
	ryu@1.0.18
	same-file@1.0.6
	semver@1.0.24
	serde@1.0.217
	serde_derive@1.0.217
	serde_json@1.0.134
	serde_spanned@0.6.8
	serde_yaml@0.9.34+deprecated
	shell-words@1.1.0
	shlex@1.3.0
	std_prelude@0.2.12
	strsim@0.11.1
	syn@2.0.95
	syn-select@0.3.0
	syntect@5.2.0
	tempfile@3.15.0
	termcolor@1.4.1
	thiserror@1.0.69
	thiserror-impl@1.0.69
	time@0.3.37
	time-core@0.1.2
	time-macros@0.2.19
	toml@0.8.19
	toml_datetime@0.6.8
	toml_edit@0.22.22
	toolchain_find@0.4.0
	unicode-ident@1.0.14
	unicode-width@0.1.14
	unicode-width@0.2.0
	unsafe-libyaml@0.2.11
	utf8parse@0.2.2
	walkdir@2.5.0
	wasi@0.11.0+wasi-snapshot-preview1
	winapi@0.3.9
	winapi-i686-pc-windows-gnu@0.4.0
	winapi-util@0.1.9
	winapi-x86_64-pc-windows-gnu@0.4.0
	windows-sys@0.48.0
	windows-sys@0.59.0
	windows-targets@0.48.5
	windows-targets@0.52.6
	windows_aarch64_gnullvm@0.48.5
	windows_aarch64_gnullvm@0.52.6
	windows_aarch64_msvc@0.48.5
	windows_aarch64_msvc@0.52.6
	windows_i686_gnu@0.48.5
	windows_i686_gnu@0.52.6
	windows_i686_gnullvm@0.52.6
	windows_i686_msvc@0.48.5
	windows_i686_msvc@0.52.6
	windows_x86_64_gnu@0.48.5
	windows_x86_64_gnu@0.52.6
	windows_x86_64_gnullvm@0.48.5
	windows_x86_64_gnullvm@0.52.6
	windows_x86_64_msvc@0.48.5
	windows_x86_64_msvc@0.52.6
	winnow@0.6.22
"

inherit cargo

DESCRIPTION="Subcommand to show the result of macro expansion and #[derive] expansion."
HOMEPAGE="https://github.com/dtolnay/cargo-expand"
SRC_URI="
	https://github.com/dtolnay/${PN}/archive/${PV}.tar.gz -> ${P}.tar.gz
	${CARGO_CRATE_URIS}
"

LICENSE="|| ( Apache-2.0 MIT )"
# Dependent crate licenses
LICENSE+=" Apache-2.0 BSD LGPL-3+ MIT Unicode-3.0"
SLOT="0"
KEYWORDS="~amd64"

RUST_MIN_VER="1.81.0"

# rust does not use *FLAGS from make.conf, silence portage warning
# update with proper path to binaries this crate installs, omit leading /
QA_FLAGS_IGNORED="usr/bin/${PN}"

src_install() {
	cargo_src_install
	einstalldocs
}
