# Copyright 2024 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.5.4-r1

EAPI=8

CRATES="
	ahash@0.8.11
	aho-corasick@1.1.3
	anstream@0.6.14
	anstyle@1.0.7
	anstyle-parse@0.2.4
	anstyle-query@1.1.0
	anstyle-wincon@3.0.3
	anyhow@1.0.86
	cfg-if@1.0.0
	clap@4.5.7
	clap_builder@4.5.7
	clap_derive@4.5.5
	clap_lex@0.7.1
	colorchoice@1.0.1
	console@0.15.8
	crop@0.3.0
	crossbeam-deque@0.8.5
	crossbeam-epoch@0.9.18
	crossbeam-utils@0.8.20
	either@1.12.0
	encode_unicode@0.3.6
	equivalent@1.0.1
	eyre@0.6.12
	getrandom@0.2.15
	glob@0.3.1
	hashbrown@0.14.5
	heck@0.5.0
	indenter@0.3.3
	indexmap@2.2.6
	indoc@2.0.5
	insta@1.39.0
	is_terminal_polyfill@1.70.0
	itertools@0.13.0
	lazy_static@1.4.0
	libc@0.2.155
	linked-hash-map@0.5.6
	memchr@2.7.2
	once_cell@1.19.0
	proc-macro-error@1.0.4
	proc-macro-error-attr@1.0.4
	proc-macro2@1.0.85
	proc-macro2-diagnostics@0.10.1
	quote@1.0.36
	rayon@1.10.0
	rayon-core@1.12.1
	regex@1.10.5
	regex-automata@0.4.7
	regex-syntax@0.8.4
	rstml@0.11.2
	rustywind_core@0.1.2
	serde@1.0.203
	serde_derive@1.0.203
	serde_spanned@0.6.6
	similar@2.5.0
	str_indices@0.4.3
	strsim@0.11.1
	syn@2.0.76
	syn_derive@0.1.8
	thiserror@1.0.61
	thiserror-impl@1.0.61
	toml@0.7.8
	toml_datetime@0.6.6
	toml_edit@0.19.15
	unicode-ident@1.0.12
	unicode-width@0.1.13
	utf8parse@0.2.2
	version_check@0.9.4
	wasi@0.11.0+wasi-snapshot-preview1
	windows-sys@0.52.0
	windows-targets@0.52.5
	windows_aarch64_gnullvm@0.52.5
	windows_aarch64_msvc@0.52.5
	windows_i686_gnu@0.52.5
	windows_i686_gnullvm@0.52.5
	windows_i686_msvc@0.52.5
	windows_x86_64_gnu@0.52.5
	windows_x86_64_gnullvm@0.52.5
	windows_x86_64_msvc@0.52.5
	winnow@0.5.40
	yansi@1.0.1
	zerocopy@0.7.34
	zerocopy-derive@0.7.34
"

inherit cargo

PRETTYPLEASE_COMMIT="bebc259d12bb0f9a53132f3700017b56d32a4dad"

DESCRIPTION="view macro formatter CLI for the Leptos web framework"
HOMEPAGE="https://github.com/bram209/leptosfmt"
SRC_URI="
	https://github.com/bram209/${PN}/archive/refs/tags/${PV}.tar.gz -> ${P}.tar.gz
	https://github.com/bram209/prettyplease/archive/${PRETTYPLEASE_COMMIT}.tar.gz
		-> leptosfmt-prettyplease-${PRETTYPLEASE_COMMIT}.tar.gz
	${CARGO_CRATE_URIS}
"

LICENSE="|| ( Apache-2.0 MIT )"
# Dependent crate licenses
LICENSE+=" Apache-2.0 MIT Unicode-DFS-2016"
SLOT="0"
KEYWORDS="~amd64"

# rust does not use *FLAGS from make.conf, silence portage warning
# update with proper path to binaries this crate installs, omit leading /
QA_FLAGS_IGNORED="usr/bin/${PN}"

src_unpack() {
	cargo_src_unpack

	rm -d "${S}/prettyplease" || die
	mv "prettyplease-${PRETTYPLEASE_COMMIT}" "${S}/prettyplease" || die
}

src_install() {
	cargo_src_install --path cli

	einstalldocs
	dodoc docs/configuration.md example_leptosfmt.toml
}
