name: CI

on:
  push:
    branches:
    - master
    paths-ignore:
    - 'README.md'
  pull_request:
    branches:
    - master
  schedule:
  - cron: "30 0 * * 6"

jobs:
  repoman:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: lucianposton/repoman-ebuild-qa-action@v1
